version: "3.9"
services:
  traefik:
    image: traefik:brie
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - api
      - priv
      - front
  
  api:
    #image: europe-central2-docker.pkg.dev/rozkladzik/timetable/api
    build: ./api
    container_name: api
    volumes:
      - "./db.sqlite:/data/db.sqlite"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.cal.isi.wtf`)"
      - "traefik.http.routers.api.entrypoints=web"
  
  scrapper:
    #image: europe-central2-docker.pkg.dev/rozkladzik/timetable/scrapper
    build: ./scrapper
    container_name: scrapper
    environment:
      - "DB_PATH=/data/db.sqlite"
      - "FROM_DATE=2022-02-01"
      - "TO_DATE=2022-10-01"
      - "TIMETABLE_URL=https://planzajec.eaiib.agh.edu.pl/view/timetable/934/events"
    volumes:
      - "./db.sqlite:/data/db.sqlite"

  ical:
    #image: europe-central2-docker.pkg.dev/rozkladzik/timetable/ical
    build: ./ical
    container_name: ical
    volumes:
      - "./db.sqlite:/data/db.sqlite"
      - "./ical/out:/data/out"
    #  - "calendars:/data/out"

  priv:
    #image: europe-central2-docker.pkg.dev/rozkladzik/timetable/priv
    build: ./priv
    container_name: priv
    expose:
      - 80
    volumes:
      - "./db.sqlite:/data/db.sqlite"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.priv.rule=Host(`plan.achook.dev`)"
      - "traefik.http.routers.priv.entrypoints=web"

  front:
    image: nginx:stable-alpine
    container_name: front
    volumes:
      - "./front/config/nginx.conf:/etc/nginx/nginx.conf"
      - "./front/dist:/var/www/html/static"
      - "./front/logs:/var/log/nginx"
      - "calendars:/var/www/html/calendars"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`cal.isi.wtf`)"
      - "traefik.http.routers.front.entrypoints=web"

  uptime:
    image: europe-docker.pkg.dev/goroczas/uptime/client
    container_name: uptime
    environment:
      INSTANCE_NAME: test

volumes:
  calendars: